name: Deploy to vercel
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
      - name: Create .vercel (link to project)
        run: |
          mkdir -p .vercel
          echo '{"projectId":"${{ env.VERCEL_PROJECT_ID }}","orgId":"${{ env.VERCEL_ORG_ID }}"}' > .vercel/project.json
      - name: Pull Vercel Environment Information
        run: vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}